### ISSUE TITLE
Make a plugin that adds Jade line/col information to the DOM

### ISSUE THREAD

**Issue by TimothyGu** [pugjs/jade#2165]
Migrated from #1879.

----

I want to create a middleware for express and jade. I'll publish it as a separate module. This module allows me to interactively open a text editor by selecting a DOM node in the browser. The text editor is opened in exactly the file and line that generated that DOM node. What I need from jade is to add an option to include filenames and line numbers in the HTML output. I've done an initial implementation. If the idea is accepted I will write tests for that.

This is how the output with this option enabled looks like:

```html
<html jade_file="/path/to/jade/examples/includes.jade" jade_line=2>
  <head jade_file="/path/to/jade/examples/includes/head.jade" jade_line=1>
    <title jade_line=2>My Site</title>
    <!-- including other jade works-->
    <script jade_file="/path/to/jade/examples/includes/scripts.jade" jade_line=1 src="/javascripts/jquery.js"></script>
    <script jade_line=2 src="/javascripts/app.js"></script>
    <!-- including .html, .css, etc works--><style>
  body {
    padding: 50px;
  }
</style>
  </head>
  <body jade_file="/path/to/jade/examples/includes.jade" jade_line=4>
    <h1 jade_line=5>My Site</h1>
    <p jade_line=6>Welcome to my super lame site.</p>
    <div jade_file="/path/to/jade/examples/includes/foot.jade" jade_line=1 id="footer">
      <p jade_line=2>Copyright (c) foobar</p>
    </div>
  </body>
</html>
```

This is a video of the feature I've built https://vimeo.com/121122160

As you can see there is a debug mode that can be toggled with a combination of key strokes and then by clicking on a DOM node the text editor opens in the file and line that generated the output. Which is going to save me A LOT of time.

As I said I only need some debug information in the HTML output. If the flag/idea is accepted to be included in jade to output this information I will complete this pull request with a new commit adding unit tests.

Thanks!

CC @gimenete, @niftylettuce, & @jantimon.

**Comment by jantimon** [comment]
Cool please let me know how I can support you.
Could you also add the "jade_file" information for the `block` part of mixins?
I had some cases where this didn't work propally.

**Comment by gimenete** [comment]
Is there any documentation about how to create plugins? Thanks!

**Comment by TimothyGu** [comment]
@jantimon said:
> I had some cases where this didn't work pro[per]ly.

Can you give an example?

@gimenete:
> Is there any documentation about how to create plugins? Thanks!

Not yet; we haven't finished implementing the infrastructure for plugins yet :)

Some related tickets:

- #2133 & #2051
- jadejs/jade-lexer#41 jadejs/jade-lexer#46
- jadejs/jade-parser#18 jadejs/jade-parser#22

----

A draft for such a plugin is at https://github.com/jadejs/jade-attr-loc. It will be published after we finish Jade v2. Right now, it adds a `data-jade-file` attribute to all tags.

**Comment by jantimon** [comment]
Hi - lines after a block don't get the expected jade-file-name: 
https://tonicdev.com/jantimon/jade-debug-bug

**Comment by TimothyGu** [comment]
@jantimon, as you can see, the <p> is in a <div> with a `jade_file`, and `jade_file` is inherited.

**Comment by jantimon** [comment]
Okay maybe it wasn't clear enough I added a more obvious example in the update:
https://tonicdev.com/jantimon/jade-debug-bug/1.1.0

```
<div jade_file="a.jade" jade_line=4 class="demo test"> 
  <h1 jade_file="b.jade" jade_line=4>demo b </h1>
  <h1 jade_file="c.jade" jade_line=5>demo c</h1>
  <p jade_line=6>demo c</p>
  <p jade_line=6>MISSING JADE FILE NAME (should be b.jade)</p>
  <p jade_line=6>MISSING JADE FILE NAME (should be a.jade)</p>
</div>
```

As you can see it is hard to tell from which files the `<p>` tags are from

**Comment by TimothyGu** [comment]
Done: https://github.com/pugjs/jade-plugin-debug-line
