### ISSUE TITLE
Include within extended block

### ISSUE THREAD

**Issue by smaili** [pugjs/jade#2172]
Say I have the following:

```jade
extends /jade/fileA

block fileABlock
    table
        tbody
            tr
                td
                    include /jade/myform
```

Jade is actually interpreting the `include` as an html tag, so the rendered output is `<include>/jade/myform</include>` instead of the actual contents of `myform` template.

**Comment by ForbesLindesay** [comment]
This should work fine.  Which version or jade are you using?

**Comment by smaili** [comment]
1.11

**Comment by ForbesLindesay** [comment]
Can you publish a Git repo with the three files needed to reproduce this.  It doesn't reproduce for me.

**Comment by smaili** [comment]
Having trouble recreating as well, but I'm certain there's a way to trigger it.

I'll go ahead and close it for now and re-open if I remember how it was done.
