### ISSUE TITLE
How to use external block in a mixin?

### ISSUE THREAD

**Issue by demsking** [pugjs/jade#2176]
Hi,
I have a block `scripts` in my `layout.jade` and I want to use it in a mixin.
I tried these codes, but they don't work like I want.

```jade
//- layout.jade
doctype html
html
  body
    block contents
       p Some content
    block scripts
```
```jade
//- mixins.jade
mixin foo(o)
   p test
   append scripts
      script(src=o.src)
```
And finally in `index.jade`
```jade
//- index.jade
extends ./layout.jade
include ./mixins.jade

//- update lines
- var o = {src: 'a/b/c/d.js'}
+foo(o)
```
Il want to add new elements in the block `scripts` from `layout.jade`. How to do that?
How to add a global block?

**Comment by PinkyJie** [comment]
I don't really understand what you want to do. Check the following snippets to see if that is what you want. 

``` jade
//- layout.jade
doctype html
html
  body
    block contents
       p Some content
    block scripts
```

``` jade
//- mixin.jade
mixin foo(o)
   p test
   script(src=o.src)
```

``` jade
//- index.jade
extends ./layout.jade
include ./mixin.jade

- var o = {src: 'a/b/c/d.js'}
block scripts
    +foo(o)

**Comment by demsking** [comment]
@PinkyJie Thanks for your reply.
Sorry, I just update the `index.jade` content.

I want to append tags in the block `scripts` when calling a mixin `foo`. 

The idea is to write components as mixins (`mixins.jade`), which used blocks defined in `layout.jade`. Then, on each new template (`index.jade`, `contact/jade`, ...), just include layout file and call mixins.

So the `index.jade` file don't needs to know the layout blocks.

**Comment by ForbesLindesay** [comment]
Mixins are used at runtime.  Extends, Includes and Blocks are at compile time.  It is not currently possible to append to a block from within a mixin.
