### ISSUE TITLE
Nesting Jade/Pug with functions or precompiled mixins

### ISSUE THREAD

**Issue by SargoDarya** [pugjs/jade#2187]
Here's what I'm trying to achieve:

**Pseudo locals**
```javascript
locals.link_to = function() {
  return '<a href="#">|</a>';
}
```

**Jade**
```jade
- link_to()
  strong Foo
  | Bar
```

**What I'd like to output in that case:**
```
<a href="#">
  <strong>Foo</strong>
  Bar
</a>
```

**What currently gets outputted:**
```
<strong>Foo</strong>
Bar
```

So my solution I guess would be to have some kind of precompiled mixin. Is something like that possible already?

**Comment by TimothyGu** [comment]
Unfortunately there is no support for a feature like this. #1950 is a more generic ticket that includes documenting the internals of how mixin functions work, including how external blocks are handled. I imagine that when #1950 is fixed this ticket should be fixed as well. Stay tuned.
