### ISSUE TITLE
Can't get script block to work

### ISSUE THREAD

**Issue by diginfo** [pugjs/jade#2190]
I seem to be unable to get unbuffred script blocks to work, this simple test:

    -
      console.log('hello world');
    
    h1 Hello World

Results in this error:

		Page Load Error.
		testa
		Error: /usr/share/nodejs/testa.jade:1 > 1
		- 2
		console.log('hello world'); 3
		4
		unexpected text - c

Yet everything works fine if I use single lines of code - What am I doing wrong ??

**Comment by TimothyGu** [comment]
It's most possible that you are not using the current version of Jade/Pug. Use `npm ls jade` to check what version you have.

**Comment by TimothyGu** [comment]
I'll close this until the necessary information is provided. I will then reopen this ticket.

**Comment by jimmytheneutrino** [comment]
Can confirm this bug. Example: https://github.com/jimmytheneutrino/testjadescriptblock

**Comment by TimothyGu** [comment]
https://github.com/jimmytheneutrino/testjadescriptblock/commit/197317b27e493d1f3a09933058cd655cc89628f4#diff-4f6ff00ce4f43d88fb822cc1482b80dcR2

**Comment by jimmytheneutrino** [comment]
Ok, removing the space fixes it. Thanks!

But maybe this behaviour could be documented or 
instead be a little bit more forgiving?
