### ISSUE TITLE
Pass inline interpolation operator in a variable

### ISSUE THREAD

**Issue by agarzola** [pugjs/jade#2192]
Using express.js, my controller looks like this:
```javascript
req.flash('errors', '#[strong Something went wrong.] Better call Saul.')
req.render('dashboard')
```

and `dashboard.jade` has something like:
```javascript
if messages.errors
  for error in messages.errors
    div(class='alert alert-danger' role='alert')= error
```

The output is:
```html
<div role="alert" class="alert alert-danger">
  #[strong Something went wrong.] Better call Saul.
</div>
```

though what I’m looking for is:
```html
<div role="alert" class="alert alert-danger">
  <strong>Something went wrong.</strong> Better call Saul.
</div>
```

As you can see, the inline interpolation operator is not getting parsed. Any way to get Jade to parse it?

**Comment by ForbesLindesay** [comment]
In server.js

```js
app.locals.jade = require('jade');
```

In your template:

```jade
if messages.errors
  for error in messages.errors
    div(class='alert alert-danger' role='alert')!= jade.render(error)
```

We don't have built in support for this because you cannot do this with un-trusted strings.  If `error` contains any un-trusted user input it could lead to an XSS attack so by default we treat the strings as plain strings and escape them appropriately.

**Comment by ForbesLindesay** [comment]
Feel free to continue discussion if you have further questions, closing as there's nothing currently wrong with jade.

**Comment by agarzola** [comment]
Sounds perfectly reasonable, @ForbesLindesay. Thanks for the prompt reply!

**Comment by agarzola** [comment]
This is resulting in the following error message:

```
TypeError: /Users/agarzola/git/cropshare-webapp/views/_partials/alert.jade:4
    2|   for error in messages.errors
    3|     - console.log(jade.render)
  > 4|     div(class='alert alert-danger' role='alert')!= jade.render(error)
    5| 
    6| if messages.success
    7|   for success in messages.success

jade.render is not a function
```

I realize that what you suggested is the best way to do this (set it once on `app.locals` and let `res` grab it from there), but just in case I also tried this in `app.js`:
```javascript
var jade = require('jade')

app.use(function (req, res, next) {
  res.locals.jade
})
```

I get the same output (as expected).

**Comment by agarzola** [comment]
When adding `- console.log(jade)` to my template, an empty object gets printed to the console: `{}`.

**Comment by agarzola** [comment]
OK, so this works:

```javascript
// app.js
app.locals.render = require('jade').render
```

```javascript
// template.jade
div(class='alert alert-danger' role='alert')!= render(error)
```

**Comment by ForbesLindesay** [comment]
I think `jade` is actually reserved.  Which I forgot about.  Using `jade` as a local will have odd effects.  Passing `render` is a much better idea.

**Comment by agarzola** [comment]
Ah, the above solution is nice, but has the adverse effect of also parsing the first word in a string that doesn’t *start* with an inline interpolation operator as a tag. So, an alert string that reads: `'Your item was added to the box.'` gets parsed as:

```html
<your>
  item was added to the box.
</your>
```

Is there an option I can pass to `jade.render()` that makes it only parse inline elements?

**Comment by ForbesLindesay** [comment]
just run `error.replace(/^/gm, '| ')` to prefix all the lines with the pipe operator.
