### ISSUE TITLE
Define tag type using code

### ISSUE THREAD

**Issue by diginfo** [pugjs/jade#2196]
Hi;

I've tried all the syntax methods I can think of but can't seem to crack this.

I would like to be able to define the tagName via code, I know this works:

    #[a()&attributes({href:'#'})]

But how can I define the tag programatically:

      -
        var mytag = {
          tag: 'a',
          attr: { href:'#', alt:'xxx'}
        }
    #[=mytag.tag()&attributes(=mytag.attr)]

Obviously this does not work, but can this be done ?

**Comment by netlovers** [comment]
How about this?
```jade
-
  var mytag = {
    tag: 'a',
    attr: { href:'#', alt:'xxx'}
  }
#{mytag.tag}()&attributes(mytag.attr)
```

**Comment by ForbesLindesay** [comment]
What @netlovers suggests looks like the solution here.
