### ISSUE TITLE
Question: JSTransformer filter options?

### ISSUE THREAD

**Issue by rstacruz** [pugjs/jade#2200]
I'd like to use [markdown-it](https://github.com/jstransformers/jstransformer-markdown-it) and pass it options like `{ html: true, typographer: true }`. How can I do that?

**Comment by rstacruz** [comment]
cool, it seems you can do this:

```
:markdown-it(html=true typographer=true)
```

Would be nice if it's in the docs too!

**Comment by deni35** [comment]
I have a similar issue.
How to pass plugins into https://github.com/jstransformers/jstransformer-markdown-it/blob/master/index.js from gulp?

**Comment by rstacruz** [comment]
that'd be hard to answer without really knowing what's between `gulp` and `jstransformer-markdown-it` in your setup.

**Comment by rstacruz** [comment]
for what it's worth, in Jade, that's:

```jade
:markdown-it(html=true typographer=true plugins=['markdown-it-decorate'])
  # Hello there
  <!-- {.center} -->
```

**Comment by deni35** [comment]
I mean to set the plugins in the gulp task.

**Comment by rstacruz** [comment]
I'm afraid you'd have to be a bit more specific than that. Might I suggest opening a stackoverflow question?

**Comment by TimothyGu** [comment]
@rstacruz 

Instead of

```
:markdown-it(html=true typographer=true)
```

you can use

```
:markdown-it(html typographer)
```

It is documented on the [master branch](https://github.com/pugjs/jade/blob/master/docs/views/reference/filters.jade#L8-L11). You are welcome to read it and see if that's clear :+1: 

@deni35 I have to agree with @rstacruz. I'm not even sure if you are using Jade/Pug from your question :)

**Comment by deni35** [comment]
From Markdown-it docs:
```
var md = require('markdown-it')()
            .use(plugin1)
            .use(plugin2, opts, ...)
            .use(plugin3);
```
How can I set these plugins with jstransformer-markdown-it? When I use jstransformer-markdown-it I haven't access to markdown-it.

**Comment by deni35** [comment]
Okey. I wrote as **rstacruz** said:
```
include:markdown-it(plugins=['./helpers/meta']) ./articles/1.md
```
But ```Cannot find module './helpers/meta'```
It's because meta.js is in my module and jstransformer-markdown-it is looking for within its module.

**Comment by rstacruz** [comment]
Ah, right. I don't know if it supports relative paths like that, but I'd try:

```
include:markdown-it(plugins=[require('path').join(process.cwd(),'helpers/meta')])
```

or better yet, move that `require('path').join(process.cwd(), 'helpers/meta')` outside Jade, and pass it onto Jade as data for your template.

**Comment by deni35** [comment]
```
[ require('path').join(process.cwd(),'helpers/meta') ]" is not constant.
```
All the same it's a very bad and hard way.

 jstransformer-markdown-it doesn't allow to setup markdown-it. Probably I need to open a new issue.

**Comment by rstacruz** [comment]
the easiest way though is to just publish your markdown-it plugin via npm :)

> jstransformer-markdown-it doesn't allow to setup markdown-it. 

it actually does, and it supports plugins too... just not plugins from relative paths.

**Comment by deni35** [comment]
**rstacruz**, do you understand that this is silly way?
I should ba able to use and my own plugins.
