### ISSUE TITLE
How to add html tag attribute with no value?

### ISSUE THREAD

**Issue by xstortionist** [pugjs/jade#2203]
I'm trying to add html tag attribute with no value but jade not rendering the way I want it.

```
section(data-off-canvas)
```

Renders to:

```
<section data-off-canvas=""></section>
```

How I need it to render:

```
<section data-off-canvas></section>
```

**Comment by TimothyGu** [comment]
That seem to work fine on http://jade-lang.com (make sure you keep the `doctype html` when testing):

![image](https://cloud.githubusercontent.com/assets/1538624/12189486/06091684-b573-11e5-8507-ffc277f4ead6.png)

Feel free to continue to comment and I'll reopen if there is an issue.

**Comment by xstortionist** [comment]
I do have doctype html - still doesn't produce the correct result

**Comment by zweifisch** [comment]
@DerekBess seems that the browser interpreted it as `<section data-off-canvas=""></section>`, the output produce by pug is correct
