### ISSUE TITLE
add async callback

### ISSUE THREAD

**Issue by DarkPark** [pugjs/jade#2206]
In case there are some file includes it's a blocking operation which is not good.
It would be nice to extend all methods with asynchronous callback as it's a common way handling file system I/O.

```js
var jade = require('jade');

// compile a function
jade.compile('string of jade with file includes', options, function ( error, fn ) {
    // render the function
    var html = fn(locals);
});
```

**Comment by TimothyGu** [comment]
Jade is designed to have a completely synchronous compile pipeline. There are several reasons for this decision, many of which are already covered in other tickets. Here're a few that just came to mind:

- Jade compilation is a CPU-intensive process that WILL BLOCK regardless of whether we are reading a file synchronously or asynchronously
- You should always cache the compiled function (`{cache: true}`) in production
- Asynchrony complicates things. A lot. And changing existing code base is a nontrivial effort

**Comment by jeromew** [comment]
for info there is the `then-jade` sub-project that allows for some asynchronous behavior in jade. It does not do asynchronous includes/extends at this stage because the 1.x engine would need too big of a modification.

sticking with @TimothyGu's advice is probably the best if streaming & asynchronous templating is not a hard requirement. You could also look into the dust templating language which is async by default.

**Comment by DarkPark** [comment]
less, node-sass, webpack and many other preprocessors are CPU-intensive as well nevertheless they have async API. In the world of node.js this approach is the de facto standard. There are a lot of warnings and articles explaining why not create fully blocking code.
So @TimothyGu I can't agree with your reasons. To be an actual modern widly-accepted solution Jade engine should evolve. Even if it requires nontrivial efforts.

**Comment by ForbesLindesay** [comment]
Given our new architecture, it would actually be pretty simple to build.  But as other people have already pointed out, it would be a complete waste of time.

Yes, webpack, browserify etc. Are all async, that doesn't make it the right thing to do.  In many cases it actually leads to worse performance.  In any case, this stage is cached, and it's really fast, and file reading is a **tiny** part of the overall performance cost.

Jade is a modern, widely accepted library, and it is evolving to be more modular and pluggable, as well as supporting new output environments such as react.

**Comment by DarkPark** [comment]
If it's this simple why not add?
It's normal practice to have both sync and async methods.

**Comment by ForbesLindesay** [comment]
Because it's not **that** simple, and it's a waste of time.  If you want to implement it, start by making an async version of [pug-loader](https://github.com/pugjs/pug-loader).  If you want to drive implementing it, we can consider it.

**Comment by jeromew** [comment]
@DarkPark for some additional infos :
 - we all agree that the more options, the better, and that people frequently request for an async behavior
 - but jade tries to be very fast in production (no i/o whatsoever when a compiled template is in cache)
 - so async includes, or async filters have not been a priority and jade will I think always support the "zero i/o"

what @ForbesLindesay suggests is that you can jump on the bandwagon of the upcoming jade 2.0 release ("pug" is the new name). Try to understand how it works, learn about the new modular architecture, and you will be able to create a plugin that does what you want.

**Comment by DarkPark** [comment]
Thanks for explanation and suggestion.
I'm sure it would be an interesting task but at the moment I'm already a little bit busy with dozens of projects :)

**Comment by ForbesLindesay** [comment]
Fair enough, At the moment I'm a little bit busy with [475 projects](https://www.npmjs.com/~forbeslindesay) so I'm sure you'll understand if we don't prioritise this.

**Comment by DarkPark** [comment]
impressive
your point is clear and fully understandable
anyway looking forward to upcoming jade 2.0 release

**Comment by fiftin** [comment]
I've implemented async/await version of pug, pug-load & pug-walk here https://github.com/mydataspace/pug-async for own needs, maybe someone will be interested. I did not spend much time on it, maybe something is missing.

**Comment by ForbesLindesay** [comment]
@fiftin Thanks for sharing. That looks like a really cool project. If you wanted to, you could add it to https://github.com/pugjs/pug#additional-resources. It would also be really cool if you updated the README to only show what's _different_ about your fork, that would probably make it much easier for people to see what the value proposition is.

**Comment by niftylettuce** [comment]
@fiftin Could you or @ForbesLindesay implement this into `pug` directly?  I would sponsor your efforts in doing so.

**Comment by ForbesLindesay** [comment]
@niftylettuce what is your specific requirement? Is it that you need to be able to load source asynchronously? If so, I would be willing to consider implementing that, if you're offering to pay for the development work. If so, please e-mail me at forbes@lindesay.co.uk and we can discuss pricing/payment.

**Comment by niftylettuce** [comment]
@ForbesLindesay 	correct, I would love to have this for https://github.com/ladjs/cache-pug-templates
