### ISSUE TITLE
Idea: compiling with include files

### ISSUE THREAD

**Issue by eschmid72** [pugjs/jade#2208]
I got many files starting like this.
```jade
include ../mixins/blade-mixins
include ../mixins/menu-mixins
include ../mixins/more-mixins

// code
```

I've been thinking, it would be cool, if you would not need to include the mixin-files in every `jade` file.
So, it would be cool if you would not need them in the files, just tell the compiler in the options, which files  it has to include.

With that feature, you could in future configure a gulpfile.js, define all include files there, and you will have global include files and don't need them having in the jade files anymore.

And - you could include mixins from a Github repository or NPM or Bower module.

**Comment by jeromew** [comment]
you could also use gulp to prepend the string "include ../mixins/blade-mixins" before the compilation task.

also I thought you include recursively (but did not try) so you could `include ../mixins/all` and in `all` include all the other files.

**Comment by eschmid72** [comment]
Ok, thanks, I will try that, then this is not really necessary, just too much work.

**Comment by tomlagier** [comment]
I wrote a Gulp plugin that does exactly this! (and can path them to your node_modules or whatever other directory you'd like)

https://github.com/tomlagier/gulp-jade-modules

**Comment by eschmid72** [comment]
great :+1:

**Comment by baoang** [comment]
Will Pug add the relative path feature so that when compiling different *.pug files, the relative paths inside will automatically updated?

http://stackoverflow.com/questions/35583911/how-to-write-the-gulp-file-when-compiling-jade-files-and-wanting-to-keep-the-rel
