### ISSUE TITLE
Issue creating script tag with async attribute

### ISSUE THREAD

**Issue by sbdchd** [pugjs/jade#2214]
I am trying to create a tag like the following.

```html
<script src='main.js' async></script>
```

I have tried

```jade
script(src='main.js', async)
```

and

```jade
script(async, src='main.js')
```

But the output has been

```html
<script async="async" src="main.js"></script>
```

and

```html
<script src="main.js" async="async"></script>
```

I am using jade version: `1.11.0`

**Comment by TimothyGu** [comment]
See:

- https://github.com/pugjs/jade/issues/237#issuecomment-1378836
- https://github.com/pugjs/jade/issues/370#issuecomment-85654654
- https://github.com/pugjs/jade/issues/816#issuecomment-10571616

**Comment by aichholzer** [comment]
None of the above see-comments points to how `async` should be handled.

**Comment by ForbesLindesay** [comment]
@aichholzer there is nothing special about async, it's exactly like all other boolean attributes. You can either pass `{doctype: 'html'}` or start your template with `doctype html` or stop caring about differences in the html output that **have no effect on the behaviour of the resulting web page**.
