### ISSUE TITLE
Add "doctype plist"

### ISSUE THREAD

**Issue by thecodechef** [pugjs/jade#2220]
Hey i just thought that would be a good addition to the doctypes

```jade
doctype plist
```
into

```xml
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

**Comment by thecodechef** [comment]
Also could fix the problem that when you write two different doctypes beside each other they end up on the same line they need to be on two different lines

**Comment by ForbesLindesay** [comment]
Please feel free to submit a pull request to https://github.com/pugjs/doctypes
