### ISSUE TITLE
Using a yield tag

### ISSUE THREAD

**Issue by tuvistavie** [pugjs/jade#2221]
I am using [RiotJS](http://riotjs.com/) with Jade to generate HTML.
In Riot, there is a `yield` tag which I am using, but obviously, it is not possible to do it directly,
as it is already used by Jade.
I am currently using the HTML syntax, but this forces me to write all the content in it in HTML, which is not very nice.
Would there be a way to use a reserved tag name, for theses kind of edge cases?

What I would like to write is something like:

```jade
my-riot-tag
  yield(to="my-destination")
    .my
       .content
          p
            | yielded by riot
            | and written in Jade (or pug maybe)
```

If there is not currently a good solution for this, I think it would be nice to have a way
to handle these kind of cases, especially with custom tags becoming more and more common
in many JS frameworks.
Maybe we could allow writing `\yield` instead of `yield` when we just want a tag and not the Jade construct.

**Comment by netlovers** [comment]
You can use it this way:
```jade
my-riot-tag
  #{'yield'}(to="my-destination")
    .my
       .content
          p
            | yielded by riot
            | and written in Jade (or pug maybe)
```

But I'm not sure if this is any nicer.

**Comment by tuvistavie** [comment]
@netlovers Thanks for the trick. At least I can write in Jade inside the yield, so this is good enough for me!
