### ISSUE TITLE
Angular 2 and jade

### ISSUE THREAD

**Issue by blacksails** [pugjs/jade#2223]
I have an issue which somewhat makes me unable to combine Angular 2 and jade.

The following jade code
```jade
input([(test1)]="test1" [(test2)]="test2")
```

translates into
```html
<input [(test1)]="test2"/>
```

Does anyone know of a workaround?

**Comment by blacksails** [comment]
I found that it works as it should with the &attributes syntax:
```jade
input&attributes({"[(test1)]": "test1", "[(test2)]": "test2"})
```
But I really dislike that syntax. I am interested in a better alternative.

**Comment by TimothyGu** [comment]
You can either quote the attributes or use a comma:

```jade
input("[(test1)]"="test1" "[(test2)]"="test2")
input([(test1)]="test1", [(test2)]="test2")
```

Otherwise the attribute is interpreted as:

```javascript
"test1" [(test2)]="test2"
("test1" [(test2)])="test2"
("test1"[test2]) = "test2"

**Comment by blacksails** [comment]
@TimothyGu Ahh thanks alot!

**Comment by Rush** [comment]
I wonder, is it possible to improve the parser to support the good old spaces and no quoting with these new attributes?

**Comment by ganySA** [comment]
+1

**Comment by ForbesLindesay** [comment]
It isn't, because `foo [bar]` is a valid JavaScript expression.  e.g. `const foo = ['a'], bar = 0; console.log(foo [bar]);` would log `a`.
