### ISSUE TITLE
local var undefined if compiling a template twice

### ISSUE THREAD

**Issue by cdaringe** [pugjs/jade#2225]
hi all:

i've been pulling my hair out for a while, but got close.  i dont understand what's going on.

in my build script i generate two compile functions:

`compileIndex` and [`compileReview`](https://github.com/cdaringe/salsa/blob/master/build.js#L64).

compileReviews runs, then compileIndex runs.  both templates use `extend './layout.jade'`.

if i remove the `extend ./layout.jade` from the first template, then `compileIndex` runs just fine.  however, if both templates extend layout.jade, when the second goes to compile, it complains that a local var `books` is `undefined`.  i [hard-coded `books` into the `compileIndex`'s locals](https://github.com/cdaringe/salsa/blob/master/build.js#L36), so it's definitely there.

i dont understand why extending a common template in both template files would be an issue, or why simply removing it from the first template file restores the passed locals as expected.

check it: https://github.com/cdaringe/salsa

pull it, npm i.  run `npm run build`.  it should puke.  then, remove the `extends`  bit from [src/review.jade](https://github.com/cdaringe/salsa/blob/master/src/review.jade#L1), try and build again, and all is well.

either there is a bug or i don't understand how locals and inheritance co-mingle!

thanks!

**Comment by TimothyGu** [comment]
Can you paste the EXACT errors as printed on the console?

**Comment by TimothyGu** [comment]
I just cloned the repo and ran `npm run build`. This showed up:

```
timothy-gu@debian-gift:/tmp/salsa$ npm run build

> salsa@1.0.0 build /tmp/salsa
> node build.js

{ [Error: ENOENT: no such file or directory, lstat 'src/images']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'src/images' }

npm ERR! Linux 4.2.0-0.bpo.1-amd64
npm ERR! argv "/home/timothy-gu/.nvm/versions/node/v5.4.1/bin/node" "/home/timothy-gu/.nvm/versions/node/v5.4.1/bin/npm" "run" "build"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! salsa@1.0.0 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the salsa@1.0.0 build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the salsa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls salsa
npm ERR! There is likely additional logging output above.
```

**Comment by TimothyGu** [comment]
After `mkdir src/images` I got the same error as you did. Here's the problem:

> i hard-coded books into the compileIndex's locals, so it's definitely there.

But you did NOT hardcode books into compileReview. These two compilation instances are completely separate. Just because you hardcoded them in one compilation doesn't mean that the compiled function somehow "stores" the values as a global which will be used by a function compiled in a another context.

To fix this, make sure that `books` are in `review` as well:

```diff
diff --git a/build.js b/build.js
index ca03844..9afb2e8 100644
--- a/build.js
+++ b/build.js
@@ -73,6 +73,7 @@ var compileReviews = function(cb) {
             buildy.reviews.data.push(review);
             if (!review.name) throw new ReferenceError('missing review name', review);
             review.subtitle = review.name;
+            review.books = [1, 2, 3];
             fs.writeFileSync(
                 path.join(outDir, 'review-' + _.kebabCase(review.name)) + '.html',
                 compileReview(review)
@@ -86,9 +87,9 @@ async.series(
     [ clean, copyAssets, compileReviews, compileIndex ],
     function(err) {
         if (err) {
-            console.error(err);
+            console.error(err.stack);
             process.exit(1);
         }
         console.log('build success');
     }
-);
\ No newline at end of file
+);
```

After the changes above the compilation succeeds.

(I also changed the `console.error` to print the stack trace)

**Comment by cdaringe** [comment]
one of those days.

thank you for taking the time to spot my bug for me.
