### ISSUE TITLE
Parse inline variables?

### ISSUE THREAD

**Issue by House3272** [pugjs/jade#2226]
Say I have json objects (myJson) with variable field names, in this cases, it happens to be 'alpha' so I set that as a variable: myjson:JSON.parse(myData), myfield:'alpha'

    tbody
      each val in myjson
        tr
          td= val.myfield

but the above obviously resolves to look for 'myfield' field within val.
Can Jade resolve it as a variable somehow?

**Comment by TimothyGu** [comment]
What is a JSON object? Is it a JSON *string* or *JavaScript* object?

Also, please give a example of `myjson` in its **entirety.**

**Comment by ForbesLindesay** [comment]
```
tbody
  each val, name in myjson
    tr
      th= name
      td= val
```
