### ISSUE TITLE
Interpolation in Comments plz

### ISSUE THREAD

**Issue by thecodechef** [pugjs/jade#2228]
hey just wanted to see if you would make it possible to do interpolation inside of single comments i can do inside of block comments but just gives me an extra step to go in my html or xml and delete lines

and btw if it is possible and i'm just not doing it right plz tell me

```jade
// Facebook: #{tag['property-name']}
// Facebook: !{tag['property-name']}
```

**Comment by ForbesLindesay** [comment]
If you want to output dynamic HTML comments, you should use:

```
<!-- Facebbok: #{tag['property-name']} -->
```

This is intentional as things which parse comments are often very picky about exact spacing, and this gives you complete control over that spacing.

**Comment by thecodechef** [comment]
Thanx
