### ISSUE TITLE
Commas in attributes?

### ISSUE THREAD

**Issue by believer-ufa** [pugjs/jade#2229]
Hello) First of all I want to say thank you for creating this wonderful template engine.

And secondly, I want to ask one little question about the attributes.

The official documentation is recommended to use the following syntax:
```jade
a(class='button', href='google.com') Google
```

But at the same time, there is no problem, if we delete a comma between attributes. Why not make it standard? After all, the absence of a comma makes reading and writing attributes even more simple pastime :)

```jade
a(class='button' href='google.com' data-otherattr='value') Google
```

**Comment by ForbesLindesay** [comment]
The comma used to be required, it's now optional.  We should probably remove it from the documentation.

**Comment by jeromew** [comment]
Did you manage to make it optional for all scenarios where the value is a javascript formula ?

**Comment by ForbesLindesay** [comment]
I'm pretty sure it's always optional.  The only case where you might needed it is if your attribute name start with a character that could be continuing a JavaScript expression e.g. :

```
- var foo = 'foo';
div(bar='whatever' +foo)
div(bar='whatever', +foo)
```

```html
<div bar="whateverfoo"></div>
<div bar="whatever" +foo="+foo"></div>
```

**Comment by dhruvdutt** [comment]
@ForbesLindesay Please check my PR. Resolved this issue.
