### ISSUE TITLE
CLI support for custom filters

### ISSUE THREAD

**Issue by FND** [pugjs/jade#2233]
As far as I can tell (cf. https://github.com/pugjs/jade/issues/1503#issuecomment-40854964), there's currently no way to use custom filters via the command line. This seems like an unfortunate limitation for otherwise simple setups (in my case: `jade -o pages templates/[^_]*`).

I imagine implementing a new option (e.g. `--plugin $require_path` or `--filter foo=$require_path`) should be fairly straightforward - but perhaps it'd be better to use the existing `--obj` mechanism instead?

**Comment by ForbesLindesay** [comment]
Moved to pugjs/pug-cli#15
