### ISSUE TITLE
How to do this in elegant way

### ISSUE THREAD

**Issue by LionNatsu** [pugjs/jade#2234]
The following Jade code doesn't work:

    p: textarea(name="content", required)
      if params.content
        =params.content
      else
        .
          # Example
          ## Example
          ...

but this works:

    p: textarea(name="content", required)
      if params.content
        =params.content
      else
        em. //I don't know why it works. It just works.
          # Example
          ## Example
          ...

compiles to this:

    <p><textarea name="content" required># Example
    ## Example
    ...

Yes, that's what I want.
Marvelous, `em` disappeared.
*In this case, `em` could be any none-self-closing element.*

1. It's a bug or feature?
2. How to use plain text block without tag like the `em`? (In most case, `em` appears AS-IS)

**Comment by ForbesLindesay** [comment]
This should work in pug@2.0.0 with just the `.`.  I suspect the `em` doesn't actually disappear (try using view-source rather than the dom inspector).  Your browser will do strange things to try and "fix" your document when it hits an error (e.g. any tag inside a textarea).

**Comment by LionNatsu** [comment]
Thanks. That was exactly using view-source to check the output, using jade@1.11.0 to compile. But some new things happened: I couldn't reproduce it now, it shows in the textarea with `<em></em>` literally. (I guest some parameter pass into jade is why I could see the text with `em`)
