### ISSUE TITLE
Not possible to create attribute without parameter

### ISSUE THREAD

**Issue by renannprado** [pugjs/jade#2237]
**Please read before answering**

First, I know that there's a solution, if I use `doctype html` in my jade file, it will generate the attribute alone such as `checked` or whatever. That's fine.

However the problem comes when I want to make use of that functionality within a partial html file, where I would have no `html`, `head`, `body` tags.

Is there a way that I can generate the html like the below without the `doctype html` or even some kind of option that would allow not to output the doctype in the actual HTML file?

Thanks

What I get now:

```
<!DOCTYPE html>
<div checked>
</div>
```

What I would like to have:

```
<div checked>
</div>
```

Edit:

I found that I can use the option `doctype: "html"` in my grunt task. Is the only way?

**Comment by ForbesLindesay** [comment]
You can also do `div(checked='')` which will compile to `<div checked=""></div>` which is pretty much always semantically equivalent.  This has been discussed at length in other issues.

**Comment by renannprado** [comment]
Well, actually they are not always the same. While working with angularJS, for example, some directives make distinction between ``directive-x=""``and ``directive-x``.
But anyway at least we have a workaround for that.
