### ISSUE TITLE
Unable to use conditionals on blocks

### ISSUE THREAD

**Issue by mememori** [pugjs/jade#2239]
If i have a template like the following
```jade
extends layout.jade

if false
  block title
    title I have a title
```

That block (_title_) will always be rendered.

The only way to execute a conditional on a block seems to be inserting the conditional _inside_ the block but that way it's advantage (of having a default value) is lost

**Comment by ForbesLindesay** [comment]
We don't support anything except blocks (and in the upcoming v2 release, mixins) at the top level of a file that uses `extends`.  This is because the `blocks` are linked together at compile time.  You can, however, do:

```jade
extends layout.jade

block title
  if false
    title I have a title
  else 
    title I have a different title
```
