### ISSUE TITLE
Can't use "for" attribute for a label in mixins

### ISSUE THREAD

**Issue by lukewatts** [pugjs/jade#2242]
I'm trying to create the following mixin and it keeps telling me for is an invalid token.

```jade
mixin label(title, for)
    label.main-menu-toggle-label(for=for)= title
```
Usage:
```jade
+label("Services", "dropdown")
```
I've tried putting in an attributes object and everything but nothing works. The minute I remove for=for it compiles.

**Comment by TimothyGu** [comment]
`for` cannot be used as a variable name.

**Comment by lukewatts** [comment]
Is that all it is?! I was at that for 40 minutes and in the end I gave up :(

Of course...because of the for statement! Ugh I'm such an idiot!

Cheers for that.

**Comment by lukewatts** [comment]
Although...a more helpful error than "Unexpected token" would be a great enhancement!

**Comment by ForbesLindesay** [comment]
This error isn't thrown by jade, it's thrown by the parser (either uglifyjs or acorn).

**Comment by lukewatts** [comment]
I see. Would there be a way of catching whatever error they throw and give more info to the end user of Jade. Or would someone have to find which one (acorn / uglifyjs) is being lazy about their Exceptions and go raise the issues on their repo?

**Comment by TimothyGu** [comment]
> Would there be a way of catching whatever error they throw and give more info to the end user of Jade.

Simply saying, it's difficult.

> Or would someone have to find which one (acorn / uglifyjs) is being lazy about their Exceptions and go raise the issues on their repo?

Really, `for` is not a "reserved word" in the sense that `enum` is. There's really no better way to say "unexpected token."

In Pug 2 we'll have column tracking, so the error might look a bit more comprehensible

```
Error: Pug:1:34
  > 1| label.main-menu-toggle-label(for=for)
----------------------------------------^

Syntax Error: Unexpected token
    at makeError (/home/timothy_gu/pug/pug-error/index.js:32:13)
    at Lexer.error (/home/timothy_gu/pug/pug-lexer/index.js:52:15)
    at Lexer.assertExpression (/home/timothy_gu/pug/pug-lexer/index.js:74:12)
    at Lexer.attrs (/home/timothy_gu/pug/pug-lexer/index.js:1065:18)
    at Lexer.callLexerFunction (/home/timothy_gu/pug/pug-lexer/index.js:1297:23)
    at Lexer.advance (/home/timothy_gu/pug/pug-lexer/index.js:1334:15)
    at Lexer.callLexerFunction (/home/timothy_gu/pug/pug-lexer/index.js:1297:23)
    at Lexer.getTokens (/home/timothy_gu/pug/pug-lexer/index.js:1353:12)
    at lex (/home/timothy_gu/pug/pug-lexer/index.js:12:42)
    at repl:1:13
```

**Comment by lukewatts** [comment]
The above would be perfect! 

A clear indication of the offending line and where in that line would be more than enough for 99% percent of the errors most people will encounter.

I just had no idea if I'd misspelled something or what. It was frustrating.

Consider me appeased :)
