### ISSUE TITLE
Use JSON file for global or template data or metadata?

### ISSUE THREAD

**Issue by dlewand691** [pugjs/jade#2243]
I'm wondering if it's possible to use a JSON file to store global and/or individual template variables similar to how the Harp static site generator is doing? I don't want to lock myself into a "CMS" and would love to have this flexibility.

Could variables be stored in a mixin to imitate this functionality? See the Harp docs here:
[http://harpjs.com/docs/development/metadata](http://harpjs.com/docs/development/metadata)

Thanks and keep up the great work on this awesome project!

**Comment by blitzprog** [comment]
```js
jadeRender(JSON.parse(require('page.json')))
```
Hmm. Isn't this simple enough already?
For global variables just include it in every render:
```js
jadeRender(Object.assign(JSON.parse(require('page.json')), { myGlobal: 123 }))
```

P.S. The [Aero framework](https://github.com/aerojs/aero) also has this feature, [loading JSON for a template by default](https://github.com/aerojs/aero/blob/master/docs/Pages.md).

**Comment by dlewand691** [comment]
Apologies for my ignorance, didn't know anything about that! I'll look into it more, thank you!
