### ISSUE TITLE
commenting out attributes

### ISSUE THREAD

**Issue by nathanhleung** [pugjs/jade#2245]
I'm trying to comment out an attribute but it doesn't seem like I can:

```jade
h1(
    /* ng-style="{ 'font-family': vm.data.fontFamily }" */
) {{vm.data.title}}
```

I checked out [the docs](http://jade-lang.com/reference/comments/) but they only address commenting out entire elements—is there a way to comment out individual attributes?

Thanks!

**Comment by TimothyGu** [comment]
Duplicate of #2209.
