### ISSUE TITLE
Type attribute is missing from nodes when custom compiler is made

### ISSUE THREAD

**Issue by billbuilder** [pugjs/jade#2251]
I'm developing an own compiler and when compile is called, I receive nodes without type attribute to able to decide what kind of node I'm dealing with.

Is there an API for that?
type attribute was present in a previous version for sure.

Thanks in advance!

I'm calling 

```javascript
jade.render(markup, options, function (err, res) { ... } );
```

**Comment by billbuilder** [comment]
Sorry, found the solution. Installed the wrong repo ... very confusing the other JADE repo ...

**Comment by ForbesLindesay** [comment]
You should use npm instead of github as your source of truth for installation.
