### ISSUE TITLE
forcing CR LF for mark-of-the-web tag compliance

### ISSUE THREAD

**Issue by jedierikb** [pugjs/jade#2252]
I need my jade file to export this string with CR LF as line endings for a working Mark-Of-The-Web tag (this tag is a microsoft thing):
`<!-- saved from url=(0014)about:internet -->`
more info here ( http://stackoverflow.com/a/2717637/62255 )

The rest of the file's line endings don't really matter to me.  Whatever Jade has been doing until today has been working great.

I am not sure how to hint to jade to process a line in the manner.  Help appreciated.

I read up on this related? issue ( https://github.com/pugjs/jade/issues/1683 ) but it does not seem to be the same problem I am running into.

**Comment by ForbesLindesay** [comment]
Just disable pretty printing (it should be disabled by default) then do:

```
!= '<!-- saved from url=(0014)about:internet -->\r\n'
```

as the first line of your template.  This will manually output the correct line terminator.
