### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by avdd** [pugjs/jade#2254]
Apparently jade is renamed, but there is scant information about this.

What do I npm install?  jade or pug or something else?  Which is the correct website?

**Comment by TimothyGu** [comment]
Right now it's still `npm i jade`, but the next version will be `npm i pug`. The website for now is still jade-lang.org, although that might change as the next release rolls in.

**Comment by avdd** [comment]
OK thanks.   (I assume you mean jade-lang.com!)

You might like to make the situation clear somewhere, and perhaps fix the github link on the website.
