### ISSUE TITLE
New lines between HTML tags are maintained in compressed output

### ISSUE THREAD

**Issue by benedfit** [pugjs/jade#2255]
Currently, when using the compressed output, the following input:
```jade
<div>Test</div>
<div>Test 2</div>

div Test
div Test2
```

yields:
```jade
<div>Test</div>
<div>Test 2</div><div>Test</div><div>Test2</div>
```

Is there a particular need for the first two tags to be output on separate lines? Can anyone think of any downsides to outputting on a single line?

**Comment by TimothyGu** [comment]
```jade
<pre>abc
| def
| ghi</pre>
```

**Comment by benedfit** [comment]
Good call. I'll look into it further as to what problems this would throw up

**Comment by ForbesLindesay** [comment]
Yes, we intentionally leave newlines between multiple consecutive lines of text.
