### ISSUE TITLE
Receiving supports

### ISSUE THREAD

**Issue by colkito** [pugjs/jade#2257]
Hi there!
Sorry about this question, I don't trying to spam you, but are you accepting donations or supports?
Because I want to give some of money to jade, but there is no donate button o something like that.
Also, I want to invite you to beerpay.io, a simple platform to monetize open source projects, like jade.

Thanks for this work!

best,
@colkito

**Comment by jeromew** [comment]
Hello,
sorry but your message sounds like spam to me so I am closing it.
Maintainers will have an opportunity to read it anyway and decide accordingly.

**Comment by colkito** [comment]
:+1:  no problem @jeromew, It's ok!

```
<disclaimer-mode>
I'm one creator of beerpay, but I just want to collaborate with this great project, jade.
</disclaimer-mode>
```

Please, let me know if can I help you in something.
cheers!

**Comment by TimothyGu** [comment]
Hi! Thank you for your support for Jade/Pug. We however do not have an official routine for receiving donations. Pure speaking on behalf of myself (not sure about other maintainers; cc @ForbesLindesay), if you have some extra cash, I would prefer you going to the following [link](http://www.msf.org/donate).

**Comment by colkito** [comment]
Great @TimothyGu, thanks for your attention and the link! :+1: 
cheers!
