### ISSUE TITLE
How can i run javascript function in jade template

### ISSUE THREAD

**Issue by mhf-ir** [pugjs/jade#2259]
I cant find any documentation for how can i run javascript function in jade template. My use case is write simple static site generator i have data fixture object return me fake text or html i wanna jade get it and use it in my template:

```
var myFunction = function(argumentOne, argumentTwo) {
     return "Sample text and more can be dynamic change"
};

```
in jade:

```
p {myFunction(32, 'hello')}
```
how can i do this i cant find any documentation for this.

thank you

**Comment by TimothyGu** [comment]
Put your function in the locals object, and then in the Jade template use the code syntax described in http://jade-lang.com/reference/code/

```jade
p= myFunction(32, 'hello')
```

**Comment by mhf-ir** [comment]
Problem is it's not simple function it's depend on huge node modules dependency. 

```
const mymoduleOne = require('moduleOne');
const mymoduleTwo = require('moduleTwo');

class MyClass
{
  static myMethod(argOne, argTwo)
  {
    return mymoduleOne.methodOne(argOne) + mymoduleTwo.methodTwo(argTwo);
  }
}
```

How can i use `MyClass.myMethod(1,'two')`  in jade now ?

**Comment by TimothyGu** [comment]
You can do

```js
// put this wherever you render the Jade templates
locals.MyClass = MyClass;
```
