### ISSUE TITLE
Files should end with line break

### ISSUE THREAD

**Issue by x0x7** [pugjs/jade#2260]
Some validators consider it correct to end files with a line break.  I looked into it and it indeed seems to be correct.

It is actually part of the posix standard for text files and helps other programs process data, particularly c programs which may assume that a file meets the standard.

An example of a common c program that evidences this is wc.  It will say the file has zero lines because by standard it does.

Seeing as Mac and Linux are both aim to be posix systems it doesn't seem off topic.  I suppose really the newline character is really just misnamed and EOL is a better name.

**Comment by TimothyGu** [comment]
... OK? What is your complaint against Jade/Pug? What files don't end with a line break? Output HTML or source JS or something else?

If you mean the output HTML, I'd like to remind you of several things.

- We don't output HTML as a file, but as a string.
- We don't have any obligation to conform to POSIX.
- Other tools like UglifyJS also don't care about the trailing `\n`.

**Comment by tomByrer** [comment]
x0x7; expect Jade to ignore the last blank line?
