### ISSUE TITLE
unexpected 'no closing bracket found' error

### ISSUE THREAD

**Issue by wjdenny** [pugjs/jade#2262]
`p #[a(href="http://www.example.com/site/index.php?p=32309") http://www.example.com/site/index.php?p=32309]`

causes the error: `The end of the string was reached with no closing bracket found.`

Changing one of the forward slashes within the inline element "fixes" it.
`p #[a(href="http://www.example.com/site/index.php?p=32309") http:/&#47;www.example.com/site/index.php?p=32309]` -> no error

using version 1.11.0 from npm

**Comment by TimothyGu** [comment]
This is a known and fixed issue in pug 2.0.
