### ISSUE TITLE
Global Variable scope within mixin

### ISSUE THREAD

**Issue by isaactzab** [pugjs/jade#2264]
I have a object variable
if I add an object element this works fine
```
- var tables = {}
- tables['mytable'] ={}
```
but if I try to add dynamically in mixin then this fail
```
- var tables ={}
mixin addTable(tablename)
    - tables[tablename] = {}

+addTable('mytable')
```

```
    1| - var tables = {}
    2| mixin addTable(tablename)
  > 3|  - tables[tablename] = {}
    4| 
Cannot set property 'mytable' of undefined
```
Please, how can I solve this?

**Comment by TimothyGu** [comment]
It works just fine here. Try

```jade
- var tables ={}
mixin addTable(tablename)
    - tables[tablename] = {}

+addTable('mytable')

!= JSON.stringify(tables)
```

in http://jade-lang.com/: it shows

```json
{"mytable":{}}
``` 

correctly.

**Comment by isaactzab** [comment]
Sorry again, but I see that your code works fine in a single file, but if I do using extends with many files this breaks.

**Is there a way to declare the tables variable as global through different files?**

file: *table.jade*
```jade
- var tables ={}
mixin addTable(tablename)
    - tables[tablename] = {}
```

file: *main.jade*
```jade
+addTable('mytable')
!= JSON.stringify(tables)
```

Compiler results
```shell
/home/user/Documents/jade/scripting/table.jade:3
	1| - var tables ={}
	2| mixin addTable(tablename)
  > 3|     - tables[tablename] = {}
	4| 
	5| 

Cannot set property 'mytable' of undefined
```

**Comment by TimothyGu** [comment]
No, you cannot do that. However, you _could_ do `locals.tables`, whose scope is the entire template.
